services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
#      - discovery.seed_hosts=opensearch-node1
#      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s" ]
      interval: 10s
      timeout: 3s
      retries: 30
    networks:
      - opensearch-net
#
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-net
    depends_on:
      opensearch-node1:
          condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5601/api/status"]
      interval: 20s
      timeout: 5s
      retries: 10
#
  opensearch-data-prepper:
    image: opensearchproject/data-prepper:latest
    container_name: opensearch-data-prepper
    volumes:
      - ./pipelines.yml:/usr/share/data-prepper/pipelines/pipelines.yml
      - ./data-prepper-config.yml:/usr/share/data-prepper/config/data-prepper-config.yml
    ports:
      - 2021:2021
    networks:
      - opensearch-net
    depends_on:
      opensearch-node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:2021/health"]
      interval: 20s
      timeout: 5s
      retries: 10

volumes:
  opensearch-data1:

networks:
  opensearch-net:
