
def audit_log_report(compartment: str) -> str:
    return (
        f"search \"{compartment}\" | "
        "where data.additionalDetails.eventId = 'sso.app.access.success' or "
        "data.additionalDetails.eventId = 'sso.app.access.failure' or "
        "data.additionalDetails.eventId = 'sso.session.create.success' or "
        "data.additionalDetails.eventId = 'sso.authentication.failure' or "
        "data.additionalDetails.eventId = 'sso.session.delete.success' or "
        "data.additionalDetails.eventId = 'sso.session.modify.success' or "
        "data.additionalDetails.eventId = 'admin.user.create.success' or "
        "data.additionalDetails.eventId = 'admin.user.activated.success' or "
        "data.additionalDetails.eventId = 'admin.user.deactivated.success' or "
        "data.additionalDetails.eventId = 'admin.user.update.success' or "
        "data.additionalDetails.eventId = 'admin.user.delete.success' or "
        "data.additionalDetails.eventId = 'admin.user.password.reset.success' or "
        "data.additionalDetails.eventId = 'admin.me.password.reset.success' or "
        "data.additionalDetails.eventId = 'admin.me.password.change.success' or "
        "data.additionalDetails.eventId = 'admin.policy.create.success' or "
        "data.additionalDetails.eventId = 'admin.rule.create.success' or "
        "data.additionalDetails.eventId = 'admin.policy.update.success' or "
        "data.additionalDetails.eventId = 'admin.rule.update.success' or "
        "data.additionalDetails.eventId = 'admin.passwordpolicy.create.success' or "
        "data.additionalDetails.eventId = 'admin.passwordpolicy.update.success' or "
        "data.additionalDetails.eventId = 'admin.grant.create.success' or "
        "data.additionalDetails.eventId = 'admin.grant.delete.success' or "
        "data.additionalDetails.eventId = 'admin.group.create.success' or "
        "data.additionalDetails.eventId = 'admin.group.add.member.success' or "
        "data.additionalDetails.eventId = 'admin.group.remove.member.success' or "
        "data.additionalDetails.eventId = 'admin.group.delete.success' or "
        "data.additionalDetails.eventId = 'admin.app.create.success' or "
        "data.additionalDetails.eventId = 'admin.app.update.success' or "
        "data.additionalDetails.eventId = 'admin.app.delete.success' or "
        "data.additionalDetails.eventId = 'admin.app.activated.success' or "
        "data.additionalDetails.eventId = 'admin.app.deactivated.success' or "
        "data.additionalDetails.eventId = 'notification.delivery.success' or "
        "data.additionalDetails.eventId = 'notification.delivery.failure' or "
        "data.additionalDetails.eventId = 'sso.auth.factor.initiated' or "
        "data.additionalDetails.eventId = 'sso.bypasscode.create.success' or "
        "data.additionalDetails.eventId = 'admin.approle.add.member.success' or "
        "data.additionalDetails.eventId = 'admin.approle.remove.member.success' "
        "| select data.additionalDetails"
    )

